### ISSUE TITLE
BPBible Czech translation

### ISSUE THREAD

**Issue by pafri** [bpbible/bpbible#4]
I've downloaded the new BPBible version, but can't see the Czech localization file in the folder with locales.

The old file sent the first time in 2013, that missed the release, is attached.

Greetings, Pavel Fric

**Comment by jonmmorgan** [comment]
Sorry if I missed something in 0.5.3, but I have no memory of Czech localization to be added.
I don't see any files attached to this issue either?

**Comment by pafri** [comment]
The previous communication with Ben Morgan via e-mail was made in 2013 and then in 2014. The upload most probably failed, because the system doesn't support such file type (.po). I've changed temporarily the extension of the file from 18. 7. 2013 to .txt for consequent renaming after download. Or if you would like the .po file to be sent, could you provide e-
[bpbible_cs.txt](https://github.com/bpbible/bpbible/files/205388/bpbible_cs.txt)
mail contact to you?

**Comment by jonmmorgan** [comment]
OK, thanks.

**Comment by jonmmorgan** [comment]
Seeing as I was having to release BPBible 0.5.3.1, I added this to the release.
